# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1752f64f8d7c10f5a06b10f937b11c5880729cf8953a0b19449fca619b0a54095426c216f54a56337ba0a5e2a3358d256e62b5e5681fc2013541b5a1a4c23e98

test:
  secret_key_base: d23d909ccfece60b98f9b40b0fc0b2b9ae9b7857388ad7b1c11462015a002c918f8e0dd6191cdf8ee262e4fd4fe07b28a5489fa1c614f8f19babf687e4dbf258

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
